/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package part1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;
import static spark.Spark.get;
import static spark.Spark.post;
import static spark.Spark.port;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // hataları detaylı olarak gösteriyor bu logger kütüphanesi
        Logger logger = LogManager.getLogger(App.class);
        logger.error("Hello worldd");

        // spark default olarak 4567. porttan çalışır heroku ise kendisi sanal makineden
        // bir port seçecek. Bu yüzden port ayarlamamız gerekiyor.
        int port = Integer.parseInt(System.getenv("PORT"));
        port(port);
        logger.error("Current port number: " + port);

        get("/", (req, res) -> "Hello world"); // sayfa çalıştırılmadan önce ilk sayfa hello world olarak gelecek
        get("/compute", // spark içindeki url
                (rq, rs) -> {
                    Map<String, String> map = new HashMap<String, String>();
                    map.put("result", "not compute.mustache");
                    return new ModelAndView(map, "compute.mustache"); // result ettiğimizde bize compute.mustache'yi
                                                                      // getirecek

                },

                // browserdeki görselleri görebilmek için yazdığımız method
                // beklediğimiz result değerini alacağız
                new MustacheTemplateEngine());

        // http post methodu yapıyoruz
        post("/compute", (req, res) -> {
            // Kalorileri string olarak aldık
            String kaloriler = req.queryParams("kaloriler");

            // klavyeden değerleri alacak
            java.util.Scanner sc1 = new java.util.Scanner(kaloriler);

            // boşluk vs gibi ayırma işlemini yapacak
            sc1.useDelimiter("[;\r\n]+");
            java.util.ArrayList<Integer> kalorilerList = new java.util.ArrayList<>();
            while (sc1.hasNext()) {

                // extra karakterler girildiğinde onları temizliyor
                int value = Integer.parseInt(sc1.next().replaceAll("\\s", ""));
                kalorilerList.add(value);

            }
            sc1.close();
            System.out.println(kalorilerList);

            // bunlarda da sadece bir tane girdi alıyor
            String yas = req.queryParams("yas").replaceAll("\\s", "");
            int yasAsaInt = Integer.parseInt(yas);

            String boy = req.queryParams("boy").replaceAll("\\s", "");
            int boyAsaInt = Integer.parseInt(boy);

            String kilo = req.queryParams("kilo").replaceAll("\\s", "");
            int kiloAsaInt = Integer.parseInt(kilo);

            // fonksiyonumuza değerleri
            boolean result = App.kaloriKontrol(kalorilerList, boyAsaInt, yasAsaInt, kiloAsaInt);

            // ilk değeri string çünkü result değerini alıyor ve sonucu da true ya da false
            // olarak veriyor
            Map<String, Boolean> map = new HashMap<String, Boolean>();
            map.put("result", result);

            // kontolleri görsel olarak çalıştırmayı sağlıyor
            return new ModelAndView(map, "compute.mustache");

        },
                new MustacheTemplateEngine());

    }

    // bir array oluşturuluyor içine integer dört tane değer alıyor
    public static boolean kaloriKontrol(ArrayList<Integer> array, int boy, int yas, int kilo) {

        int toplam = 0, kalori = 0;
        // arrayin içi boş değilse bu işlemleri yapacak
        if (array != null) {
            // arrayın içindeki integer değerleri toplayacak ve toplam değişkenine atayacak
            for (int i : array) {
                toplam += i;
            }
            // girilen değerlerden kalori adlı değişkenin formülü hesaplanacak
            kalori = (int) (10 * kilo + 6.25 * boy - 5 * yas + 5);

            // herhangi bir değer 0'dan küçük girildiği zaman false değeri gönderecektir.
            if (boy <= 0 && kilo <= 0 && yas <= 0) {
                return false;
            } else {

                // eğer toplam değeri kalori değerinden büyükse false değeri dönederecek
                if (toplam > kalori) {
                    return false; // * gerekenden fazla kalori
                }
                // eğer toplam değeri kaloriye eşit veya kaloriden küçükse true değeri
                // dönderecektir.
                if (toplam == kalori || kalori > toplam) {

                    return true;
                }

            }

        }
        if (array == null) {
            return false;
        }

        return false;
    }

}
